services:
  - type: web
    name: teamup-backend
    env: docker
    dockerfilePath: ./be/Dockerfile
    dockerContext: ./be
    plan: free
    region: singapore
    branch: deploy
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
