spring.application.name=main

# ---------------- dotenv ----------------
# dotenv.enabled=true

# ---------------- Database ----------------
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}


# ---------------- Google Cloud ----------------
google.GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
google.GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
google.GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
google.GOOGLE_GRANT_TYPE=${GOOGLE_GRANT_TYPE}
google.GOOGLE_LINK_GET_TOKEN=${GOOGLE_LINK_GET_TOKEN}
google.GOOGLE_LINK_GET_USER_INFO=${GOOGLE_LINK_GET_USER_INFO}
# ---------------- admin ----------------
google.ADMIN_EMAIL=${ADMIN_EMAIL}
